### ISSUE TITLE
environment.Rmd 

### ISSUE THREAD

**Issue by EmiDt** [sylvainschmitt/PhD#2]
![image](https://user-images.githubusercontent.com/37191141/37865994-006968de-2f63-11e8-9f8f-636bf2662017.png)
J'ai essayé de faire tourner ton script , et je suis bloquée pour ici pour avec les données gapcar créer le fichier gap.Rdata il faut dcm.

Si non pour le reste ca c'est bien passer il va juste pas oublié de charger le package rgeos

**Comment by sylvainschmitt** [comment]
Apparemment tu as un soucis mémoire avec le package `raster` ce qui n'est pas étonnant vu la résolution et l'emprise du MNC. D'abord si nécessaire nettoie bien ton environnement de travail de tout les objets inutiles. Ensuite utilise les fonctions d'écriture `writeRaster` et de lecture `raster` du package `raster` pour décharger ce qui est en mémoire vive (regarde l'aide du package). Une autre solution peut être de réaliser l'opération sur Tabebuia qui n'aura pas de soucis de mémoire vive et de récupérer le fichier final du raster. En attendant je t'envoie l'image R du raster que tu es sensée obtenir.

**Comment by sylvainschmitt** [comment]
Pour information j'utilise effectivement 6Go de RAM au moment de l'opération !
