### ISSUE TITLE
gap data transformation to d_gap

### ISSUE THREAD

**Issue by EmiDt** [sylvainschmitt/PhD#3]
![image](https://user-images.githubusercontent.com/37191141/37983493-07db8f16-31ca-11e8-9f13-5715abf4ba6e.png)

J'ai enfin pu faire tourner le script sur tabebuia et obtenir les données gap cependant il y a de nouveau un soucis cette fois-ci avec la fonction mask avec l'erreur : "Error in p@polygons[[i]] : indice hors limites"

Aussi ligne 163 c'est "subset" et pas "subest"

**Comment by sylvainschmitt** [comment]
Est-ce que tu peu sauver le subset de gap qui est l'opération la plus lourde et me le partager pour que je test l'erreur ?

**Comment by sylvainschmitt** [comment]
Ok, le soucis vient simplement du fait que ton objet gap est vide après le subset ! Du coup il ne peux faire de calcul dessus. Le threshold de 4 était arbitraire en attendant de faire tourner le code. Et il semblerait qu'il faille mieux définir la projection pour que le calcul de l'air se fasse bien en mètre (i.e. si l'unité de la projection est le kilomètre et que tu lui dit de garder les trouées faisant plus de 4 kilomètres carrés cela ne peut pas fonctionner). Pour ça il faut reprojeter gap avec par exemple le crs de log_gap qui lui est bien défini : 
```
proj4string(log_gap)
[1] "+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"
proj4string(gap) <- proj4string(log_gap)
```
